## Acrylic主题配置文件
############################################################################################################
# 为避免主题更新后，配置文件被覆盖，请复制一份此文件到站点根目录下的_config.Acrylic.yml文件中，修改_config.Acrylic.yml文件中的配置
############################################################################################################
# 修改此文件前，请仔细阅读官方文档：https://next-docs.acrylic.org.cn/
############################################################################################################


# 站点设置
site:
  name:                   # 左上角显示内容
    class:  text          #i_class/text/img 
    custom: 哇子       #自定义内容
  siteIcon: https://image.wazicode.top/blog/202307060036148.png # 网页icon
  icon: https://image.wazicode.top/blog/202307060036148.png     # 页脚的icon、加载动画默认的icon
  icp: 蜀ICP备2023022177号                      # ICP

# 导航栏
nav:
#导航栏左侧
  left:
    enable: true
    menu:
      我的:
        博客:
          icon: https://image.wazicode.top/blog/202307060036148.png
          url: /
        哇记:
          icon: /img/nav/top.png
          url: https://doc.wazicode.top
# 导航栏内容
  menu:
    首页:
      url: /
    文库:
      url: false
      child:
        文章列表:
          url: /archives/
          icon: fas fa-box-archive
        全部分类:
          url: /categories/
          icon: fas fa-cube
        全部标签:
          url: /tags/
          icon: fas fa-tags
    友链:
      url: false
      child:
        友情链接:
          url: /links/
          # icon: fas fa-user-group
          icon: fa-solid fa-user-group
    关于:
      url: false
      child:
        读过:
          url: /book/
          icon: fas fa-book-open
        # 看过:
        #   url: /
        #   icon: fas fa-compact-disc
        站长:
          url: /about/
          icon: fa-solid fa-user


# 导航栏右侧快捷菜单
  right: # @todo 允许用户自定义
    travellings: false   #开往
    random: true        #
    console: true       #控制台

# heo式顶部一大坨
hometop:
  bbtime: false
  banner:
    enable: true
    title: 分享技术<br>与热爱生活
    url: blog.wazicode.top
    icon:
      AE:
        img: /img/icon/ae.png
        color: '#989bf8'
      Sketch:
        img: /img/icon/Sketch.png
        color: '#ffffff'
      Docker:
        img: /img/icon/docker.png
        color: '#57b6e6'
      ps:
        img: /img/icon/ps.png
        color: '#4082c3'
      FinalCutPro:
        img: /img/icon/FinalCutPro.png
        color: '#ffffff'
      Python:
        img: /img/icon/Python.png
        color: '#ffffff'
      Swift:
        img: /img/icon/Swift.png
        color: '#eb6840'
      Principle:
        img: /img/icon/Principle.png
        color: '#8f55ba'
      illustrator:
        img: /img/icon/illustrator.png
        color: '#f29e39'
      CSS3:
        img: /img/icon/CSS3.png
        color: '#2c51db'
      JS:
        img: /img/icon/JS.png
        color: '#f7cb4f'
      Git:
        img: /img/icon/git.png
        color: '#df5b40'

  categoryGroup:
    G1:
      name: 关于站长
      icon: fas fa-dove
      url: /about/
    G2:
      name: 热门文章
      icon: fas fa-burn
      url: /archives/
    G3:
      name: 实用教程
      icon: fas fa-book
      url: https://doc.wazicode.top

  recommendList:
    sup: 置顶文章
    title: 精选文章，帮你快人一步
    url: /
    img: https://img0.baidu.com/it/u=742839054,695122920&fm=253&fmt=auto&app=138&f=JPEG?w=750&h=500
    color: '#006a73'

# 个人卡片
aside:
  home:
    noSticky: "about,flip"
    Sticky: "newestPost,allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about,flip"
    Sticky: "newestPost,allInfo"

  card:
    img: https://image.wazicode.top/blog/202307060036148.png
    sticker: https://image.wazicode.top/blog/202308162349049.png
    content: 有人说：" 照片和视频都是有记忆的，每次翻开思绪就会拉回到以前的某一天。"我想，博客也是
    information:
      Github:
        icon: fa-brands fa-github
        url: https://github.com/JustMiaoWa
      BiliBili:
        icon: fa-brands fa-bilibili
        url: https://space.bilibili.com/3493285851040490
    button:
      text: 个人主页
      url: /about/

  flip:
    color: '#0099FF'
    face:
      title: QQ群
      desc: 加入技术交流群与我们交流
    backface:
      title: 扫一扫
      desc: 获取最新信息和帮助
      img: https://image.wazicode.top/blog/202305210142013.jpg

  toc: 
    post: true
    page: false

  # 建站时间
  siteinfo:
    postcount: true
    wordcount: true
    pv: false
    uv: false
    updatetime: false
    runtimeenable: true
    runtime: '2023-05-12 00:00:00'

# 页脚
footer:
  information:
    left:
      Github:
        icon: fa-brands fa-github
        url: https://github.com/JustMiaoWa
      Gitee:
        icon: fa-brands fa-git-alt
        url: https://gitee.com/justmiaowa
      Mail:
        icon: fa-solid fa-envelope
        url: mailto:1421372365@qq.com
      笔记文档:
        icon: fa-brands fa-vuejs
        url: https://doc.wazicode.top
    right:
      CSDN:
        icon: fa-brands fa-cuttlefish
        url: https://blog.csdn.net/2301_77878360
      bilibili:
        icon: fa-brands fa-bilibili
        url: https://space.bilibili.com/3493285851040490
      抖音:
        icon: fa-brands fa-tiktok
        url: https://www.douyin.com/user/MS4wLjABAAAAQiqBXfhMVd95tw4e4mYcdTXeTJ6TAr2TtLE9bxZIZKbS1tCAc5HbY6RhKwCWZAQd
      掘金:
        icon: fa-solid fa-angles-down
        url: https://juejin.cn/user/1884997357418663
  group:
    导航:
      文章归档: /archives/
      文章分类: /categories/
      文章标签: /tags/
      友链: /link/
    服务:
      51la统计: https://51.la/
      百度统计: https://tongji.baidu.com/
    Acrylic:
      主题官网: https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next
      Github: https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next
    隐私:
      版权协议: /copyright/
      隐私政策: /privacy/
      服务条款: /terms/
      cookie政策: /cookie/
    推荐友链:
      Heo: https://blog.zhheo.com/
      Akilar: https://akilar.top

  randomlink: false

page:
  error: true
  tags: true
  categories: true
  default:
    cover: /img/hello.jpg   

# 文章页默认设置
post:
  default:
    cover: https://image.wazicode.top/blog/202305142347631.jpg
    locate: 成都
    copyright: 原创
  meta:
    date: true
    updated: true
    locate: true
    wordcount: true
    readtime: true
    pv: false
    comment: true      
  award:
    enable: true
    wechat:  https://image.wazicode.top/blog/202311122249790.jpg
    alipay: https://image.wazicode.top/blog/202311122249805.jpg
    url:  /about#award
  covercolor: #文章cover取色
    enable: false
    local: true  

# 关于界面
about: true

# 404页面
errorpage:
  img: /img/acrylic.png
  text: 页面走丢了
  recommendList: true

# 懒加载
lazyload:
  enable: false
  placeholder: /img/acrylic.png
  errorimg: /img/acrylic.png

# 图片灯箱
lightbox: true

#代码高亮增强
hightlight:
  enable: true
  hightlimit: 200

# 加载动画
loading:
  fullpage: true
  pace: true

# 第三方设置
thirdparty:
  wordcount: true
  busuanzi: 
    enable: false
    usecomment: false #当评论系统开启时文章页面使用评论系统的统计数据
  search:
    algolia_search:
      enable: false
      # hits:
      #   per_page: 6
    local_search:
      enable: true
      preload: false
      CDN:
    
  aplayer:
    enable: true
    server: tencent
    id: 8892472058      

# 评论
comment:
  enable: true
  twikoo:
    envId: https://twikoo.wazicode.top/
    # envId: https://comment-one-chi.vercel.app/
    # region: ap-shanghai
    path: window.location.pathname


# 插入代码到头部 </head> 之前 和 底部 </body> 之前
# 插入额外代码 如：统计，广告等
extends: 
  head: # 在head中插入
    - <script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js"></script>
    - <script>LA.init({id:"3FrkFGKtRNxFicUH",ck:"3FrkFGKtRNxFicUH",hashMode:true})</script>
  body: # 在body中插入

# 非必要勿动
cdn:
  head:
    pacejs: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/pace/1.2.4/pace.min.js
    fontawesomecss: https://cdn.bootcdn.net/ajax/libs/font-awesome/6.4.0/css/all.min.css
    snackbarcss: /lib/snackbar.min.css
    qrcodejs: /lib/qrcode.min.js
    twikoojs: https://cdn.staticfile.org/twikoo/1.6.19/twikoo.all.min.js
    # twikoojs: /lib/twikoo.min.js
    instantsearch: https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/instantsearch.js/4.39.0/instantsearch.production.min.js
    algolia: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/algoliasearch/4.12.1/algoliasearch-lite.umd.min.js
  body:
    swipercss: /lib/swiper.min.css
    pjaxjs: /lib/pjax.min.js
    lazyloadjs: /lib/lazyload.min.js
    snackbarjs: /lib/snackbar.min.js
    viewimagejs: /lib/view-image.min.js
    waterfalljs: /lib/waterfall.min.js
    swiperjs: /lib/swiper.min.js
    busuanzijs: https://npm.elemecdn.com/penndu@1.0.0/bsz.js
    aplayercss: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.css
    aplayerjs: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.js
    # metingjs: https://cdn1.tianli0.top/npm/meting@2.0.1/dist/Meting.min.js
    metingjs: lib/meting.min.js